apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodpanda-deployment
  labels:
    app: foodpanda-be
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: foodpanda-be
  template:
    metadata:
      labels:
        app: foodpanda-be
    spec:
      containers:
      - name: foodpanda-depoyment-container
        image: 03322504719/foodpanda-be:v1
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: foodpanda-service
  labels:
    app: foodpanda-deployment
spec:
  selector:
    app: foodpanda-deployment
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
